CREATE TABLE IF NOT EXISTS review_history (
    id INT AUTO_INCREMENT PRIMARY KEY,
    review_id VARCHAR(255) NOT NULL,
    location_id VARCHAR(255) NOT NULL,
    action VARCHAR(50) NOT NULL,
    old_reply TEXT,
    new_reply TEXT,
    old_sentiment VARCHAR(50),
    new_sentiment VARCHAR(50),
    old_emotion VARCHAR(50),
    new_emotion VARCHAR(50),
    old_attributes VARCHAR(500),
    new_attributes VARCHAR(500),
    old_quality_score INT,
    new_quality_score INT,
    gmb_posted BOOLEAN DEFAULT FALSE,
    gmb_error VARCHAR(500),
    modified_by VARCHAR(255),
    details JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_review_id (review_id),
    INDEX idx_location_id (location_id),
    INDEX idx_action (action),
    INDEX idx_created_at (created_at)
);
